pod 'Typhoon', '~> 3.4'
pod 'ReactiveCocoa', '~> 2.4'
pod 'AFNetworking', '~> 2.5'
pod 'AFNetworking-RACExtensions', '~> 0.1'
pod 'Realm', '~> 0.96'
pod 'Realm+JSON', '~> 0.2'
pod 'SDWebImage', '~> 3.0'
pod 'HCYoutubeParser', '~> 0.0.4'